
#include "config.hpp"
#include <iostream>
using namespace std;
int main() {

cout << "# This file was autogenerated." << endl
     << "# Do not modify it or your changes will be overwritten!" << endl;


#ifdef ENGINE
cout << "DEF ENGINE = 1" << endl;
#else
cout << "DEF ENGINE = 0" << endl;
#endif

#ifdef BD
cout << "DEF BD = 1" << endl;
#else
cout << "DEF BD = 0" << endl;
#endif

#ifdef EVENT_DEBUG
cout << "DEF EVENT_DEBUG = 1" << endl;
#else
cout << "DEF EVENT_DEBUG = 0" << endl;
#endif

#ifdef PTENSOR_DEBUG
cout << "DEF PTENSOR_DEBUG = 1" << endl;
#else
cout << "DEF PTENSOR_DEBUG = 0" << endl;
#endif

#ifdef NO_INTRA_NB
cout << "DEF NO_INTRA_NB = 1" << endl;
#else
cout << "DEF NO_INTRA_NB = 0" << endl;
#endif

#ifdef CG_DNA
cout << "DEF CG_DNA = 1" << endl;
#else
cout << "DEF CG_DNA = 0" << endl;
#endif

#ifdef GAUSSRANDOMCUT
cout << "DEF GAUSSRANDOMCUT = 1" << endl;
#else
cout << "DEF GAUSSRANDOMCUT = 0" << endl;
#endif

#ifdef GRID_DEBUG
cout << "DEF GRID_DEBUG = 1" << endl;
#else
cout << "DEF GRID_DEBUG = 0" << endl;
#endif

#ifdef CONSTRAINTS
cout << "DEF CONSTRAINTS = 1" << endl;
#else
cout << "DEF CONSTRAINTS = 0" << endl;
#endif

#ifdef ONEPART_DEBUG
cout << "DEF ONEPART_DEBUG = 1" << endl;
#else
cout << "DEF ONEPART_DEBUG = 0" << endl;
#endif

#ifdef LB_GPU
cout << "DEF LB_GPU = 1" << endl;
#else
cout << "DEF LB_GPU = 0" << endl;
#endif

#ifdef VIRTUAL_SITES
cout << "DEF VIRTUAL_SITES = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES = 0" << endl;
#endif

#ifdef ROTATIONAL_INERTIA
cout << "DEF ROTATIONAL_INERTIA = 1" << endl;
#else
cout << "DEF ROTATIONAL_INERTIA = 0" << endl;
#endif

#ifdef LJ_WARN_WHEN_CLOSE
cout << "DEF LJ_WARN_WHEN_CLOSE = 1" << endl;
#else
cout << "DEF LJ_WARN_WHEN_CLOSE = 0" << endl;
#endif

#ifdef BOND_ENDANGLEDIST_HARMONIC
cout << "DEF BOND_ENDANGLEDIST_HARMONIC = 1" << endl;
#else
cout << "DEF BOND_ENDANGLEDIST_HARMONIC = 0" << endl;
#endif

#ifdef TK
cout << "DEF TK = 1" << endl;
#else
cout << "DEF TK = 0" << endl;
#endif

#ifdef MEMBRANE_COLLISION
cout << "DEF MEMBRANE_COLLISION = 1" << endl;
#else
cout << "DEF MEMBRANE_COLLISION = 0" << endl;
#endif

#ifdef GAY_BERNE
cout << "DEF GAY_BERNE = 1" << endl;
#else
cout << "DEF GAY_BERNE = 0" << endl;
#endif

#ifdef POLY_DEBUG
cout << "DEF POLY_DEBUG = 1" << endl;
#else
cout << "DEF POLY_DEBUG = 0" << endl;
#endif

#ifdef BOND_ENDANGLEDIST
cout << "DEF BOND_ENDANGLEDIST = 1" << endl;
#else
cout << "DEF BOND_ENDANGLEDIST = 0" << endl;
#endif

#ifdef RANDOM_DEBUG
cout << "DEF RANDOM_DEBUG = 1" << endl;
#else
cout << "DEF RANDOM_DEBUG = 0" << endl;
#endif

#ifdef GAUSSIAN
cout << "DEF GAUSSIAN = 1" << endl;
#else
cout << "DEF GAUSSIAN = 0" << endl;
#endif

#ifdef BOND_ANGLEDIST
cout << "DEF BOND_ANGLEDIST = 1" << endl;
#else
cout << "DEF BOND_ANGLEDIST = 0" << endl;
#endif

#ifdef ESK_DEBUG
cout << "DEF ESK_DEBUG = 1" << endl;
#else
cout << "DEF ESK_DEBUG = 0" << endl;
#endif

#ifdef COMFIXED
cout << "DEF COMFIXED = 1" << endl;
#else
cout << "DEF COMFIXED = 0" << endl;
#endif

#ifdef INTER_RF
cout << "DEF INTER_RF = 1" << endl;
#else
cout << "DEF INTER_RF = 0" << endl;
#endif

#ifdef MMM1D_GPU
cout << "DEF MMM1D_GPU = 1" << endl;
#else
cout << "DEF MMM1D_GPU = 0" << endl;
#endif

#ifdef HAT
cout << "DEF HAT = 1" << endl;
#else
cout << "DEF HAT = 0" << endl;
#endif

#ifdef PARTICLE_DEBUG
cout << "DEF PARTICLE_DEBUG = 1" << endl;
#else
cout << "DEF PARTICLE_DEBUG = 0" << endl;
#endif

#ifdef BUCKINGHAM
cout << "DEF BUCKINGHAM = 1" << endl;
#else
cout << "DEF BUCKINGHAM = 0" << endl;
#endif

#ifdef FORCE_DEBUG
cout << "DEF FORCE_DEBUG = 1" << endl;
#else
cout << "DEF FORCE_DEBUG = 0" << endl;
#endif

#ifdef DPD_MASS
cout << "DEF DPD_MASS = 1" << endl;
#else
cout << "DEF DPD_MASS = 0" << endl;
#endif

#ifdef SD_DEBUG
cout << "DEF SD_DEBUG = 1" << endl;
#else
cout << "DEF SD_DEBUG = 0" << endl;
#endif

#ifdef EK_DEBUG
cout << "DEF EK_DEBUG = 1" << endl;
#else
cout << "DEF EK_DEBUG = 0" << endl;
#endif

#ifdef CONFIGTEMP
cout << "DEF CONFIGTEMP = 1" << endl;
#else
cout << "DEF CONFIGTEMP = 0" << endl;
#endif

#ifdef OIF_GLOBAL_FORCES
cout << "DEF OIF_GLOBAL_FORCES = 1" << endl;
#else
cout << "DEF OIF_GLOBAL_FORCES = 0" << endl;
#endif

#ifdef NPT
cout << "DEF NPT = 1" << endl;
#else
cout << "DEF NPT = 0" << endl;
#endif

#ifdef CUDA_DEBUG
cout << "DEF CUDA_DEBUG = 1" << endl;
#else
cout << "DEF CUDA_DEBUG = 0" << endl;
#endif

#ifdef EK_DOUBLE_PREC
cout << "DEF EK_DOUBLE_PREC = 1" << endl;
#else
cout << "DEF EK_DOUBLE_PREC = 0" << endl;
#endif

#ifdef INTEG_DEBUG
cout << "DEF INTEG_DEBUG = 1" << endl;
#else
cout << "DEF INTEG_DEBUG = 0" << endl;
#endif

#ifdef GHMC
cout << "DEF GHMC = 1" << endl;
#else
cout << "DEF GHMC = 0" << endl;
#endif

#ifdef DPD_MASS_LIN
cout << "DEF DPD_MASS_LIN = 1" << endl;
#else
cout << "DEF DPD_MASS_LIN = 0" << endl;
#endif

#ifdef SCAFACOS_DIPOLES
cout << "DEF SCAFACOS_DIPOLES = 1" << endl;
#else
cout << "DEF SCAFACOS_DIPOLES = 0" << endl;
#endif

#ifdef STAT_DEBUG
cout << "DEF STAT_DEBUG = 1" << endl;
#else
cout << "DEF STAT_DEBUG = 0" << endl;
#endif

#ifdef COMFORCE
cout << "DEF COMFORCE = 1" << endl;
#else
cout << "DEF COMFORCE = 0" << endl;
#endif

#ifdef LB_BOUNDARIES
cout << "DEF LB_BOUNDARIES = 1" << endl;
#else
cout << "DEF LB_BOUNDARIES = 0" << endl;
#endif

#ifdef GHOST_FLAG
cout << "DEF GHOST_FLAG = 1" << endl;
#else
cout << "DEF GHOST_FLAG = 0" << endl;
#endif

#ifdef HERTZIAN
cout << "DEF HERTZIAN = 1" << endl;
#else
cout << "DEF HERTZIAN = 0" << endl;
#endif

#ifdef IMMERSED_BOUNDARY
cout << "DEF IMMERSED_BOUNDARY = 1" << endl;
#else
cout << "DEF IMMERSED_BOUNDARY = 0" << endl;
#endif

#ifdef DPD_MASS_RED
cout << "DEF DPD_MASS_RED = 1" << endl;
#else
cout << "DEF DPD_MASS_RED = 0" << endl;
#endif

#ifdef MULTI_TIMESTEP
cout << "DEF MULTI_TIMESTEP = 1" << endl;
#else
cout << "DEF MULTI_TIMESTEP = 0" << endl;
#endif

#ifdef EK_ELECTROSTATIC_COUPLING
cout << "DEF EK_ELECTROSTATIC_COUPLING = 1" << endl;
#else
cout << "DEF EK_ELECTROSTATIC_COUPLING = 0" << endl;
#endif

#ifdef _P3M_GPU_FLOAT
cout << "DEF _P3M_GPU_FLOAT = 1" << endl;
#else
cout << "DEF _P3M_GPU_FLOAT = 0" << endl;
#endif

#ifdef BOND_ANGLEDIST_HARMONIC
cout << "DEF BOND_ANGLEDIST_HARMONIC = 1" << endl;
#else
cout << "DEF BOND_ANGLEDIST_HARMONIC = 0" << endl;
#endif

#ifdef GAUSSRANDOM
cout << "DEF GAUSSRANDOM = 1" << endl;
#else
cout << "DEF GAUSSRANDOM = 0" << endl;
#endif

#ifdef VERLET_DEBUG
cout << "DEF VERLET_DEBUG = 1" << endl;
#else
cout << "DEF VERLET_DEBUG = 0" << endl;
#endif

#ifdef CATALYTIC_REACTIONS
cout << "DEF CATALYTIC_REACTIONS = 1" << endl;
#else
cout << "DEF CATALYTIC_REACTIONS = 0" << endl;
#endif

#ifdef PARTIAL_PERIODIC
cout << "DEF PARTIAL_PERIODIC = 1" << endl;
#else
cout << "DEF PARTIAL_PERIODIC = 0" << endl;
#endif

#ifdef LENNARD_JONES
cout << "DEF LENNARD_JONES = 1" << endl;
#else
cout << "DEF LENNARD_JONES = 0" << endl;
#endif

#ifdef ELECTROKINETICS
cout << "DEF ELECTROKINETICS = 1" << endl;
#else
cout << "DEF ELECTROKINETICS = 0" << endl;
#endif

#ifdef HALO_DEBUG
cout << "DEF HALO_DEBUG = 1" << endl;
#else
cout << "DEF HALO_DEBUG = 0" << endl;
#endif

#ifdef BOND_ANGLE
cout << "DEF BOND_ANGLE = 1" << endl;
#else
cout << "DEF BOND_ANGLE = 0" << endl;
#endif

#ifdef LJ_ANGLE
cout << "DEF LJ_ANGLE = 1" << endl;
#else
cout << "DEF LJ_ANGLE = 0" << endl;
#endif

#ifdef ESIF_DEBUG
cout << "DEF ESIF_DEBUG = 1" << endl;
#else
cout << "DEF ESIF_DEBUG = 0" << endl;
#endif

#ifdef GHOST_FORCE_DEBUG
cout << "DEF GHOST_FORCE_DEBUG = 1" << endl;
#else
cout << "DEF GHOST_FORCE_DEBUG = 0" << endl;
#endif

#ifdef OVERLAPPED
cout << "DEF OVERLAPPED = 1" << endl;
#else
cout << "DEF OVERLAPPED = 0" << endl;
#endif

#ifdef EK_BOUNDARIES
cout << "DEF EK_BOUNDARIES = 1" << endl;
#else
cout << "DEF EK_BOUNDARIES = 0" << endl;
#endif

#ifdef VIRTUAL_SITES_RELATIVE
cout << "DEF VIRTUAL_SITES_RELATIVE = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES_RELATIVE = 0" << endl;
#endif

#ifdef CELL_DEBUG
cout << "DEF CELL_DEBUG = 1" << endl;
#else
cout << "DEF CELL_DEBUG = 0" << endl;
#endif

#ifdef SCAFACOS
cout << "DEF SCAFACOS = 1" << endl;
#else
cout << "DEF SCAFACOS = 0" << endl;
#endif

#ifdef LATTICE_DEBUG
cout << "DEF LATTICE_DEBUG = 1" << endl;
#else
cout << "DEF LATTICE_DEBUG = 0" << endl;
#endif

#ifdef FFT_DEBUG
cout << "DEF FFT_DEBUG = 1" << endl;
#else
cout << "DEF FFT_DEBUG = 0" << endl;
#endif

#ifdef LB_BOUNDARIES_GPU
cout << "DEF LB_BOUNDARIES_GPU = 1" << endl;
#else
cout << "DEF LB_BOUNDARIES_GPU = 0" << endl;
#endif

#ifdef BMHTF_NACL
cout << "DEF BMHTF_NACL = 1" << endl;
#else
cout << "DEF BMHTF_NACL = 0" << endl;
#endif

#ifdef MOLFORCES_DEBUG
cout << "DEF MOLFORCES_DEBUG = 1" << endl;
#else
cout << "DEF MOLFORCES_DEBUG = 0" << endl;
#endif

#ifdef EK_REACTION
cout << "DEF EK_REACTION = 1" << endl;
#else
cout << "DEF EK_REACTION = 0" << endl;
#endif

#ifdef ADDITIONAL_CHECKS
cout << "DEF ADDITIONAL_CHECKS = 1" << endl;
#else
cout << "DEF ADDITIONAL_CHECKS = 0" << endl;
#endif

#ifdef MODES
cout << "DEF MODES = 1" << endl;
#else
cout << "DEF MODES = 0" << endl;
#endif

#ifdef EXTERNAL_FORCES
cout << "DEF EXTERNAL_FORCES = 1" << endl;
#else
cout << "DEF EXTERNAL_FORCES = 0" << endl;
#endif

#ifdef TABULATED
cout << "DEF TABULATED = 1" << endl;
#else
cout << "DEF TABULATED = 0" << endl;
#endif

#ifdef LATTICE
cout << "DEF LATTICE = 1" << endl;
#else
cout << "DEF LATTICE = 0" << endl;
#endif

#ifdef ELECTROSTATICS
cout << "DEF ELECTROSTATICS = 1" << endl;
#else
cout << "DEF ELECTROSTATICS = 0" << endl;
#endif

#ifdef H5MD_DEBUG
cout << "DEF H5MD_DEBUG = 1" << endl;
#else
cout << "DEF H5MD_DEBUG = 0" << endl;
#endif

#ifdef FENE_DEBUG
cout << "DEF FENE_DEBUG = 1" << endl;
#else
cout << "DEF FENE_DEBUG = 0" << endl;
#endif

#ifdef COMM_DEBUG
cout << "DEF COMM_DEBUG = 1" << endl;
#else
cout << "DEF COMM_DEBUG = 0" << endl;
#endif

#ifdef H5MD
cout << "DEF H5MD = 1" << endl;
#else
cout << "DEF H5MD = 0" << endl;
#endif

#ifdef LANGEVIN_PER_PARTICLE
cout << "DEF LANGEVIN_PER_PARTICLE = 1" << endl;
#else
cout << "DEF LANGEVIN_PER_PARTICLE = 0" << endl;
#endif

#ifdef METADYNAMICS
cout << "DEF METADYNAMICS = 1" << endl;
#else
cout << "DEF METADYNAMICS = 0" << endl;
#endif

#ifdef SOFT_SPHERE
cout << "DEF SOFT_SPHERE = 1" << endl;
#else
cout << "DEF SOFT_SPHERE = 0" << endl;
#endif

#ifdef VIRTUAL_SITES_NO_VELOCITY
cout << "DEF VIRTUAL_SITES_NO_VELOCITY = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES_NO_VELOCITY = 0" << endl;
#endif

#ifdef LJCOS
cout << "DEF LJCOS = 1" << endl;
#else
cout << "DEF LJCOS = 0" << endl;
#endif

#ifdef LENNARD_JONES_GENERIC
cout << "DEF LENNARD_JONES_GENERIC = 1" << endl;
#else
cout << "DEF LENNARD_JONES_GENERIC = 0" << endl;
#endif

#ifdef VIRTUAL_SITES_THERMOSTAT
cout << "DEF VIRTUAL_SITES_THERMOSTAT = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES_THERMOSTAT = 0" << endl;
#endif

#ifdef MASS
cout << "DEF MASS = 1" << endl;
#else
cout << "DEF MASS = 0" << endl;
#endif

#ifdef AFFINITY
cout << "DEF AFFINITY = 1" << endl;
#else
cout << "DEF AFFINITY = 0" << endl;
#endif

#ifdef DIPOLAR_DIRECT_SUM
cout << "DEF DIPOLAR_DIRECT_SUM = 1" << endl;
#else
cout << "DEF DIPOLAR_DIRECT_SUM = 0" << endl;
#endif

#ifdef DP3M
cout << "DEF DP3M = 1" << endl;
#else
cout << "DEF DP3M = 0" << endl;
#endif

#ifdef MORSE_DEBUG
cout << "DEF MORSE_DEBUG = 1" << endl;
#else
cout << "DEF MORSE_DEBUG = 0" << endl;
#endif

#ifdef ROTATION_PER_PARTICLE
cout << "DEF ROTATION_PER_PARTICLE = 1" << endl;
#else
cout << "DEF ROTATION_PER_PARTICLE = 0" << endl;
#endif

#ifdef NEMD
cout << "DEF NEMD = 1" << endl;
#else
cout << "DEF NEMD = 0" << endl;
#endif

#ifdef SD_NOT_PERIODIC
cout << "DEF SD_NOT_PERIODIC = 1" << endl;
#else
cout << "DEF SD_NOT_PERIODIC = 0" << endl;
#endif

#ifdef P3M
cout << "DEF P3M = 1" << endl;
#else
cout << "DEF P3M = 0" << endl;
#endif

#ifdef VIRTUAL_SITES_DEBUG
cout << "DEF VIRTUAL_SITES_DEBUG = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES_DEBUG = 0" << endl;
#endif

#ifdef ESR_DEBUG
cout << "DEF ESR_DEBUG = 1" << endl;
#else
cout << "DEF ESR_DEBUG = 0" << endl;
#endif

#ifdef _P3M_GPU_DOUBLE
cout << "DEF _P3M_GPU_DOUBLE = 1" << endl;
#else
cout << "DEF _P3M_GPU_DOUBLE = 0" << endl;
#endif

#ifdef GHOSTS_HAVE_BONDS
cout << "DEF GHOSTS_HAVE_BONDS = 1" << endl;
#else
cout << "DEF GHOSTS_HAVE_BONDS = 0" << endl;
#endif

#ifdef LB_DEBUG
cout << "DEF LB_DEBUG = 1" << endl;
#else
cout << "DEF LB_DEBUG = 0" << endl;
#endif

#ifdef MOLFORCES
cout << "DEF MOLFORCES = 1" << endl;
#else
cout << "DEF MOLFORCES = 0" << endl;
#endif

#ifdef GHOST_DEBUG
cout << "DEF GHOST_DEBUG = 1" << endl;
#else
cout << "DEF GHOST_DEBUG = 0" << endl;
#endif

#ifdef EWALD_GPU
cout << "DEF EWALD_GPU = 1" << endl;
#else
cout << "DEF EWALD_GPU = 0" << endl;
#endif

#ifdef FFTW
cout << "DEF FFTW = 1" << endl;
#else
cout << "DEF FFTW = 0" << endl;
#endif

#ifdef BOND_CONSTRAINT
cout << "DEF BOND_CONSTRAINT = 1" << endl;
#else
cout << "DEF BOND_CONSTRAINT = 0" << endl;
#endif

#ifdef TUNABLE_SLIP
cout << "DEF TUNABLE_SLIP = 1" << endl;
#else
cout << "DEF TUNABLE_SLIP = 0" << endl;
#endif

#ifdef HYDROGEN_BOND
cout << "DEF HYDROGEN_BOND = 1" << endl;
#else
cout << "DEF HYDROGEN_BOND = 0" << endl;
#endif

#ifdef COS2
cout << "DEF COS2 = 1" << endl;
#else
cout << "DEF COS2 = 0" << endl;
#endif

#ifdef COULOMB_DEBYE_HUECKEL
cout << "DEF COULOMB_DEBYE_HUECKEL = 1" << endl;
#else
cout << "DEF COULOMB_DEBYE_HUECKEL = 0" << endl;
#endif

#ifdef LJCOS2
cout << "DEF LJCOS2 = 1" << endl;
#else
cout << "DEF LJCOS2 = 0" << endl;
#endif

#ifdef SD
cout << "DEF SD = 1" << endl;
#else
cout << "DEF SD = 0" << endl;
#endif

#ifdef SMOOTH_STEP
cout << "DEF SMOOTH_STEP = 1" << endl;
#else
cout << "DEF SMOOTH_STEP = 0" << endl;
#endif

#ifdef MAGGS_DEBUG
cout << "DEF MAGGS_DEBUG = 1" << endl;
#else
cout << "DEF MAGGS_DEBUG = 0" << endl;
#endif

#ifdef THERMOSTAT_IGNORE_NON_VIRTUAL
cout << "DEF THERMOSTAT_IGNORE_NON_VIRTUAL = 1" << endl;
#else
cout << "DEF THERMOSTAT_IGNORE_NON_VIRTUAL = 0" << endl;
#endif

#ifdef DPD
cout << "DEF DPD = 1" << endl;
#else
cout << "DEF DPD = 0" << endl;
#endif

#ifdef LJGEN_SOFTCORE
cout << "DEF LJGEN_SOFTCORE = 1" << endl;
#else
cout << "DEF LJGEN_SOFTCORE = 0" << endl;
#endif

#ifdef SD_USE_FLOAT
cout << "DEF SD_USE_FLOAT = 1" << endl;
#else
cout << "DEF SD_USE_FLOAT = 0" << endl;
#endif

#ifdef INTER_DPD
cout << "DEF INTER_DPD = 1" << endl;
#else
cout << "DEF INTER_DPD = 0" << endl;
#endif

#ifdef VIRTUAL_SITES_COM
cout << "DEF VIRTUAL_SITES_COM = 1" << endl;
#else
cout << "DEF VIRTUAL_SITES_COM = 0" << endl;
#endif

#ifdef LJ_DEBUG
cout << "DEF LJ_DEBUG = 1" << endl;
#else
cout << "DEF LJ_DEBUG = 0" << endl;
#endif

#ifdef LB
cout << "DEF LB = 1" << endl;
#else
cout << "DEF LB = 0" << endl;
#endif

#ifdef MPI_CORE
cout << "DEF MPI_CORE = 1" << endl;
#else
cout << "DEF MPI_CORE = 0" << endl;
#endif

#ifdef BOND_VIRTUAL
cout << "DEF BOND_VIRTUAL = 1" << endl;
#else
cout << "DEF BOND_VIRTUAL = 0" << endl;
#endif

#ifdef OLD_DIHEDRAL
cout << "DEF OLD_DIHEDRAL = 1" << endl;
#else
cout << "DEF OLD_DIHEDRAL = 0" << endl;
#endif

#ifdef SD_FF_ONLY
cout << "DEF SD_FF_ONLY = 1" << endl;
#else
cout << "DEF SD_FF_ONLY = 0" << endl;
#endif

#ifdef CUDA
cout << "DEF CUDA = 1" << endl;
#else
cout << "DEF CUDA = 0" << endl;
#endif

#ifdef LEES_EDWARDS
cout << "DEF LEES_EDWARDS = 1" << endl;
#else
cout << "DEF LEES_EDWARDS = 0" << endl;
#endif

#ifdef PARTICLE_ANISOTROPY
cout << "DEF PARTICLE_ANISOTROPY = 1" << endl;
#else
cout << "DEF PARTICLE_ANISOTROPY = 0" << endl;
#endif

#ifdef LB_ELECTROHYDRODYNAMICS
cout << "DEF LB_ELECTROHYDRODYNAMICS = 1" << endl;
#else
cout << "DEF LB_ELECTROHYDRODYNAMICS = 0" << endl;
#endif

#ifdef P3M_DEBUG
cout << "DEF P3M_DEBUG = 1" << endl;
#else
cout << "DEF P3M_DEBUG = 0" << endl;
#endif

#ifdef UMBRELLA
cout << "DEF UMBRELLA = 1" << endl;
#else
cout << "DEF UMBRELLA = 0" << endl;
#endif

#ifdef MORSE
cout << "DEF MORSE = 1" << endl;
#else
cout << "DEF MORSE = 0" << endl;
#endif

#ifdef FORCE_CORE
cout << "DEF FORCE_CORE = 1" << endl;
#else
cout << "DEF FORCE_CORE = 0" << endl;
#endif

#ifdef DIPOLES
cout << "DEF DIPOLES = 1" << endl;
#else
cout << "DEF DIPOLES = 0" << endl;
#endif

#ifdef THERMO_DEBUG
cout << "DEF THERMO_DEBUG = 1" << endl;
#else
cout << "DEF THERMO_DEBUG = 0" << endl;
#endif

#ifdef ROTATION
cout << "DEF ROTATION = 1" << endl;
#else
cout << "DEF ROTATION = 0" << endl;
#endif

#ifdef SHANCHEN
cout << "DEF SHANCHEN = 1" << endl;
#else
cout << "DEF SHANCHEN = 0" << endl;
#endif

#ifdef TRANS_DPD
cout << "DEF TRANS_DPD = 1" << endl;
#else
cout << "DEF TRANS_DPD = 0" << endl;
#endif

#ifdef LE_DEBUG
cout << "DEF LE_DEBUG = 1" << endl;
#else
cout << "DEF LE_DEBUG = 0" << endl;
#endif

#ifdef COLLISION_DETECTION
cout << "DEF COLLISION_DETECTION = 1" << endl;
#else
cout << "DEF COLLISION_DETECTION = 0" << endl;
#endif

#ifdef FLATNOISE
cout << "DEF FLATNOISE = 1" << endl;
#else
cout << "DEF FLATNOISE = 0" << endl;
#endif

#ifdef OIF_LOCAL_FORCES
cout << "DEF OIF_LOCAL_FORCES = 1" << endl;
#else
cout << "DEF OIF_LOCAL_FORCES = 0" << endl;
#endif

#ifdef TWIST_STACK
cout << "DEF TWIST_STACK = 1" << endl;
#else
cout << "DEF TWIST_STACK = 0" << endl;
#endif

#ifdef ASYNC_BARRIER
cout << "DEF ASYNC_BARRIER = 1" << endl;
#else
cout << "DEF ASYNC_BARRIER = 0" << endl;
#endif

#ifdef EXCLUSIONS
cout << "DEF EXCLUSIONS = 1" << endl;
#else
cout << "DEF EXCLUSIONS = 0" << endl;
#endif

}
